'''🎯 Guess the Number Game
Description:
The "Guess the Number" game is a simple yet addictive Python project where the computer randomly generates a number between 1 and 100. The player has 7 chances to guess the correct number.

How to Play:

The computer picks a random number between 1 and 100.
The player enters their guess.
The game provides feedback:
If the guess is too high, it tells you to guess lower.
If the guess is too low, it suggests guessing higher.
If the guess is correct, it celebrates your win! 🎉
The player gets a maximum of 7 attempts to guess the number.
'''



import random

while True:
    print("\nHello! You have 7 chances to guess the number generated by the computer for you.")
    
    chances = 7
    guesses = 0
    num_to_guess = random.randint(1, 100)  # Ensure the number is between 1 and 100
    
    while guesses < chances:
        guessed_num = int(input("\nEnter your guess: "))
        guesses += 1

        if guessed_num == num_to_guess:
            print(f"Congratulations! You guessed the number {num_to_guess} in {guesses} attempts!")
            break
        elif guessed_num < num_to_guess:
            print("Too low! Try guessing a higher number.")
        else:
            print("Too high! Try guessing a lower number.")
    
    if guessed_num != num_to_guess:
        print(f"Oops! You've used all {chances} attempts. The correct number was {num_to_guess}.")

    again = input("\nWould you like to play again? (yes/no): ").strip().lower()
    if again != 'yes':
        print("Thanks for playing! Goodbye.")
        break  # Exit the loop if the user does not want to play again
